- name: installtion and configuration of Catalogue server
  hosts: all
  become: yes
  tasks:
  - name: instlattion of catalogue
    yum:
       name:  nodejs make gcc-c++ -y
       state:  present




