- name: installation and configuration of Catalogue server
  hosts: all
  become: yes
  tasks:
  - name: installation of catalogue
    yum:
       name: [ "nodejs", "make", "gcc-c++" ]
       state: present

  - name: creation of user ID
    user:
      name: roboshop
      group: wheel

  - name: Download catalogue docs from GITHUB
    ansible.builtin.unarchive:
      src: https://github.com/roboshop-devops-project/catalogue/archive/main.zip
      dest: /tmp
      remote_src: yes

  - name: Copyng static content to nginx from default location
      ansible.builtin.copy:
        src: /tmp/catalogue-main/
        dest: /home/roboshope/catalogue/
        remote_src: yes
        owner: roboshop
        group: roboshop
  - name: install  catalogue dependencices
    community.general.npm:
       path: /home/roboshop/catalogue
       state: latest
       become_user: roboshop




