- name: installation and configuration of Catalogue server
  hosts: all
  become: yes
  tasks:
  - name: installation of catalogue
    yum:
       name:  nodejs
       state: present
  - name: creation of user ID
    user:
      name: roboshop
      group: wheel

  - name: Download catalogue docs from GITHUB
    ansible.builtin.unarchive:
      src: https://github.com/roboshop-devops-project/catalogue/archive/main.zip
      dest: /tmp
      remote_src: yes

  - name: Copyng static content to nginx from default location
      ansible.builtin.copy:
        src: /tmp/catalogue-main
        dest: /tmp/catalogue
        remote_src: yes





