- name: installation and configuration of Catalogue server
  hosts: all
  become: yes
  tasks:
  - name: installation of catalogue
    yum:
       name:  nodejs
       state: present
  - name: creation of user ID
    ansible.builtin.user:
      name: roboshop
      group: wheel






