- name: installtion and configuraiton of nginx
  hosts: all
  tasks:
    - name: installtion of nginx
      become: yes
      yum:
         name: nginx
         state: present
    - name: starting of nginx service status
      service:
          name: nginx
          state: enable
    - name: starting of nginx service status
      service:
          name: nginx
          state: started

